// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package server

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DashboardDataResponse DashboardDataResponse
type DashboardDataResponse struct {
	Items  *[]Items `json:"items,omitempty"`
	Status *int     `json:"status,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Detail     *string `json:"detail,omitempty"`
	StatusCode *int    `json:"status_code,omitempty"`
}

// HealthStatusResponse Health Check Response Information
type HealthStatusResponse struct {
	Message *string `json:"message,omitempty"`
	Status  *int    `json:"status,omitempty"`
}

// InventoryCount defines model for InventoryCount.
type InventoryCount struct {
	// CalculatedAt The timestamp of when the inventory count was calculated.
	CalculatedAt *time.Time `json:"calculated_at,omitempty"`

	// CatalogObjectId The ID of the catalog object (item variation).
	CatalogObjectId *string `json:"catalog_object_id,omitempty"`

	// CatalogObjectType The type of the catalog object.
	CatalogObjectType *string `json:"catalog_object_type,omitempty"`

	// LocationId The ID of the location where the inventory is tracked.
	LocationId *string `json:"location_id,omitempty"`

	// Quantity The new inventory quantity as a string.
	Quantity *string `json:"quantity,omitempty"`

	// State The inventory state.
	State *string `json:"state,omitempty"`
}

// Items defines model for Items.
type Items struct {
	ItemName              *string `json:"item_name,omitempty"`
	NormalInventoryCount  *int    `json:"normal_inventory_count,omitempty"`
	ReserveInventoryCount *int    `json:"reserve_inventory_count,omitempty"`
	SecureInventoryCount  *int    `json:"secure_inventory_count,omitempty"`
}

// SquareWebhook defines model for SquareWebhook.
type SquareWebhook struct {
	// CreatedAt The timestamp of when the event was created.
	CreatedAt time.Time   `json:"created_at"`
	Data      WebhookData `json:"data"`

	// EventId A unique ID for the event.
	EventId openapi_types.UUID `json:"event_id"`

	// MerchantId The ID of the merchant associated with the event.
	MerchantId string `json:"merchant_id"`

	// Type The type of the event.
	Type string `json:"type"`
}

// WebhookData defines model for WebhookData.
type WebhookData struct {
	// Id The ID of the data object.
	Id     *openapi_types.UUID `json:"id,omitempty"`
	Object *struct {
		InventoryCounts *[]InventoryCount `json:"inventory_counts,omitempty"`
	} `json:"object,omitempty"`

	// Type The type of the data object.
	Type *string `json:"type,omitempty"`
}

// SquareRequestJSONRequestBody defines body for SquareRequest for application/json ContentType.
type SquareRequestJSONRequestBody = SquareWebhook
